import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { uuid } from 'uuidv4';

@table("langwire_prod_text_inputs")
class Query {
    @autoGeneratedHashKey()
    uuid!: string;

    @attribute()
    created_at: string;

    @attribute()
    updated_at: string; 

    @attribute()
    contents!: string;

    @attribute()
    output_conll!: string;

    @attribute()
    user_id!: number;

    constructor(){
        this.created_at = new Date().toISOString();
        this.updated_at = this.created_at;
        this.uuid = uuid(); 
    }
}

export default Query;