import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table("langwire_prod_text_inputs")
class Query {
    @autoGeneratedHashKey()
    uuid!: string;

    @attribute()
    created_at: Date;

    @attribute()
    updated_at: Date; // Should be assigned to be equal to created_at on initialization;

    @attribute()
    contents!: string;

    @attribute()
    output_conll!: string;

    @attribute()
    user_id!: number;

    constructor(){
        this.created_at = new Date();
        this.updated_at = this.created_at;
    }
}

export default Query;